### ISSUE TITLE
Don't require Action to return a Result

### ISSUE THREAD

**Issue by jjant** [evenorog/undo#17]
Some actions can't error, so it's annoying to be forced to do so. I think you could just remove that and have the output associated type be a result if needed.

**Comment by evenorog** [comment]
The containers needs to check if the action was successful before proceeding, e.g. in Record::apply. Not sure how this would be handled without returning Result. Maybe when specialization is stable?

I think most actions will fail when undo and redo is involved, as long as it is not short example snippets.
