### ISSUE TITLE
Question: Example of merge actions?

### ISSUE THREAD

**Issue by Dicklessgreat** [evenorog/undo#18]
Doc says;
Actions can be [merge](https://docs.rs/undo/latest/undo/trait.Action.html#method.merge)d into a single action by implementing the merge method on the action.

So I did like that...

```
struct Add(String);

impl Action for Add {
    type Target = String;
    type Output = ();
    type Error = &'static str;

    fn apply(&mut self, s: &mut String) -> undo::Result<Add> {
        s.push_str(&self.0.clone());
        Ok(())
    }

    fn undo(&mut self, s: &mut String) -> undo::Result<Add> {
        self.0 = s.pop().ok_or("s is empty")?.into();
        Ok(())
    }

    fn merge(&mut self, other : &mut Self) -> undo::Merged
        where
            Self: Sized, {
        self.0.push_str(&other.0);
        undo::Merged::Yes
    }
}

```

But I couldn't find a way to merge actions from `History` or `Record`.
```
    let mut target = String::new();
    let mut history = History::new();
    history.apply(&mut target, Add('a'.into())).unwrap();
    history.apply(&mut target, Add('b'.into())).unwrap();
    history.apply(&mut target, Add('c'.into())).unwrap();
    assert_eq!(target, "abc");
    //===Procedure that merge actions into an action...===
    history.undo(&mut target).unwrap().
    assert_eq!(target, "");
```
Suppose I want to make `target` empty by one "undo", then how "===Procedure that merge actions into an action...===" section should be?
Can someone give me more details on how to merge them?

**Comment by evenorog** [comment]
They are merged but in the undo method you need to change from popping the last character to popping off the length of the new string. Try changing Action::undo to `self.0 = s.split_off(s.len() - self.0.len());`.

**Comment by Dicklessgreat** [comment]
Oh, sorry you are right, Thanks.
But even if I modify as you told, I'm still stuck.

Let's see the example. I want to merge three actions (`Add('a'.into())`, `Add('b'.into())`, and `Add('c'.into())`) into one action, and then, by one undo(by the line `history.undo(&mut target).unwrap();`), I want to make the `target` empty.

`//===Procedure that merge actions into an action...===` is not comments but a place holder where I want you to answer the right instructions. What should it be like? I suppose I can do something to merge actions there, but I couldn't find one. 
Or, am I on totally wrong direction? Then, how `merge()` should be used?

**Comment by evenorog** [comment]
You do not need to do anything for them to be merged, the merged method is called every time you call the apply method and if it returns Yes the second command is not stored. Your code should work now, and you can try calling `redo` at the bottom of your code and you will see that the target is empty after undo and "abc" after calling redo again.

**Comment by Dicklessgreat** [comment]
Oh!! I got it!
I misunderstood I had to call some method to merge because Doc says ["manual"](https://docs.rs/undo/0.47.2/undo/trait.Action.html#method.merge) lol
Thanks for your answer. That should help my advance.

**Comment by evenorog** [comment]
No problem! "manual" means that you need to _implement_ the merge method yourself instead of it being done automatically by the library.
