### ISSUE TITLE
Reference to the inner Action list

### ISSUE THREAD

**Issue by imsamuka** [evenorog/undo#20]
Can the crate provide a reference (at least immutable) to the Action list inside `Record`, `Timeline` and `History`?

Without it, there's no way to, for example, display the history in a Gtk TreeView, as each leaf needs detailed typed information.
As far as I know, there's no way to do it using the `Display` struct provided.

In my case, i need to inspect the history after adding things to it, and act accordingly.
But currently I can't.

**Comment by evenorog** [comment]
Sounds good. I will add it in the next release.
