### ISSUE TITLE
0.49 breaks compatibility with `wasm32-unknown-unknown` target

### ISSUE THREAD

**Issue by Quantum64** [evenorog/undo#24]
Regression in 0.49, as 0.48 works fine. Panic due to unimplemented `SystemTime`.

`panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:31:9`

**Comment by evenorog** [comment]
Does `wasm32-unknown-unknown` not support `std`?

**Comment by bolli24** [comment]
This issue persists in 0.52.

`wasm32-unknown-unknown` does support some parts of the standard library, but not everything (eg `std::fs`, `std::thread::spawn`). Among those are `std::Instant::now()` and `std::SystemTime::now()`. The latter is used in this project. 

To allow the use of the `now()` functions on wasm target you can use [web_time](https://github.com/daxpedda/web-time) which implements `Instant` and `SystemTime` using JS-based timestamps for wasm targets and re-exports from `std::time` for everything else.

**Comment by evenorog** [comment]
Using `std` is optional and you can disable it if you need to build for `wasm32-unknown-unknown`.
