### ISSUE TITLE
feat(history): branches detail

### ISSUE THREAD

**Issue by wongjiahau** [evenorog/undo#28]
I'm trying to use [`History`](https://docs.rs/undo/latest/undo/history/struct.History.html) to implement the Undo Tree feature in my editor, however, there's no direct method to query details of the branches except using the [`display`](https://docs.rs/undo/latest/undo/history/struct.History.html#method.display) method.

I propose the following methods to be added:

1. `fn branch_len() -> usize`
2. `fn branch_actions(branch_index: usize) -> Range<At>`

**Comment by evenorog** [comment]
Yeah currently there is no way to do it.

I'm planning to expose the `Branch` struct in history and let the user get the information they need that way.

I'll try to work on it this week and release a new version soon.

**Comment by wongjiahau** [comment]
Thank you 🙏

**Comment by evenorog** [comment]
@wongjiahau I think the new api in #29 will close this issue. Let me know if something is missing.

**Comment by wongjiahau** [comment]
I'm able to achieve what I wanted using the new `History::get_branch` and `Branch::parent` methods, but I think it will be more natural if `Branch` exposes the method `Branch::first_node(&self) -> At`, which is essentially one node after the branch's parent node.

Because I can only switch the root branch by going to the first node of the target branch, not the parent node.

It can be even more direct, if `History` exposes methods that enable the switch of root branch:
- `fn go_to_previous_branch(&mut self, &mut E::Target) -> Vec<E::Output>` : Goes to the first node of the previous branch
- `fn go_to_next_branch(&mut self, &mut E::Target) -> Vec<E::Output>` : Goes to the first node of the next branch

**Comment by evenorog** [comment]
You can switch root branch as long as you just know the id of the new root.

```rust
let head = history.head();
history.go_to(&mut target, At::new(1, head.index));
```

Something like this would take you to the new root (1 in this case) at the current index, and you can now undo and redo on the new root. I could add this as a separate method that just takes in the branch id that you want to go to, if it is a common use case.

I'm not sure what you mean by previous and next branch in this case. I don't store any of that information currently so think that would be hard to do.

**Comment by wongjiahau** [comment]
Sorry that my previous explanation is not clear enough, I'm not sure if by looking at this [code snippet](https://github.com/wongjiahau/treeman/commit/bdaedecfd29e6617e0d58e42b61025f06db76f50#diff-63e4a32005d14798be0b74e9cea1ebd03ea1b6005f5d675f2d5e5b48c724a07bR435-R460), it would make sense to you what switching to the next or previous branch mean.

Say I have the following history:
```
* 2-4 [HEAD] 
* 2-3 
| * 0-4 
| * 0-3 
|/
| * 1-4 
| * 1-3 
|/
* 2-2 
* 2-1 
* 2-0 [SAVED]
```

By going to the previous branch, I mean moving `[HEAD]` to `1-3`, and by going to the previous branch again, I mean moving `[HEAD]` to `0-3`.
And when `[HEAD]` is at `0-3`, going to the next branch means moving `[HEAD]` to `1-3`.

It is basically the same operation as you provided in the code snippet, but the **separate method** should not need to take the `branch_id` argument, as it should be able to determine what's the next and the previous branch.

**Comment by evenorog** [comment]
Thanks for the explanation! I don't want to add more go_to versions right now, but I have added `next_branch_head` and `prev_branch_head` methods to history that i believe should do what you want. So now you can do:

```rust
if let Some(prev) = history.prev_branch_head() {
   history.go_to(&mut target, prev);
}
```

I will probably release a new version this weekend.

**Comment by wongjiahau** [comment]
Those will do too. Thanks!
