### ISSUE TITLE
Unable to create a History without providing type information

### ISSUE THREAD

**Issue by shueja** [evenorog/undo#32]
`let history = History::<_>::builder().limit(10).capacity(10).build();`
gives the error:
```
error[E0282]: type annotations needed for `History<E>`      
   --> src\main.rs:157:17
    |
157 |             let history = History::<_>::builder().limit(10).capacity(10).build();
    |                 ^^^^^^^   ----------------------- type must be known at this point
    |
help: consider giving `history` an explicit type, where the type for type parameter `E` is specified
    |
157 |             let history: History<E> = History::<_>::builder().limit(10).capacity(10).build();
```
What am I supposed to put for the type information?

**Comment by evenorog** [comment]
You need to create a type that implements the Edit trait.
In my examples I'm using the Add as you can see in the readme, but you need to create your own and use that for the type.

**Comment by shueja** [comment]
Okay I misunderstood the library then and created several different “actions” that implement Edit and tried to use them all.

I ended up making my own solution loosely based on yours, but it might be worth a clarification in documentation, that it only supports one Edit implementor.

**Comment by evenorog** [comment]
You can just use an enum for the edit command when you want multiple different actions.
