### ISSUE TITLE
chain/merged removed; non-transitive merging

### ISSUE THREAD

**Issue by Evylon** [evenorog/undo#8]
Hi,

first of all thank you for developing this lib. It helps me a great deal with my current hobby project.

Now, this might be more of a question than an issue. I was planning to merge certain commands depending on the preceding command, which should be possible by implementing the merge method. However, if I understand correctly, merging is always transitive because all mergable Commands share the same id for merging. i.e. if A merges with B and B with C, A also merges with C, even if I do not want to merge A and C if there was no B in between. How can I prevent this?

I saw that there used to be the Merged/Chain struct that would allow me to manually create such a chain of commands, but chain.rs got removed. What is the reason for this or did I misunderstand this somehow and the desired behaviour can still be realized without a Chain.

Kind regards
Evylon

**Comment by evenorog** [comment]
Hi!

If you are using version 0.39 from crates.io the Chain structure is still available, and you can do it like this: `let _ = Chain::new().join(cmd1).join(cmd2).join(cmd3);`.

If you are using version 0.40 from github, you can do it like this: `let _ = Join::new(cmd1, cmd2).join(cmd3);`.

**Comment by Evylon** [comment]
Ah, so that's what happend. Looks good, thanks for the quick response!
Cheers and keep the good work up!

**Comment by evenorog** [comment]
Thanks! :+1:
